[build]
  publish = "."

[[redirects]]
  from = "/sitemap.xml/"
  to = "/sitemap.xml"
  status = 301
  force = true

[[redirects]]
  from = "/robots.txt/"
  to = "/robots.txt"
  status = 301
  force = true
